[package]
name = "shitcoin"
version = "0.1.0"
authors = ["asventon1 <asventon1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.0"
rsa = "0.5.0"
rand = "0.8.4"